// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using testKetNoi.Models;

namespace testKetNoi.Data
{
    public partial class DataContext : DbContext
    {
        public DataContext()
        {
        }

        public DataContext(DbContextOptions<DataContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DangKyKTX> DangKyKTX { get; set; }
        public virtual DbSet<DongPhuc> DongPhuc { get; set; }
        public virtual DbSet<HoSo> HoSo { get; set; }
        public virtual DbSet<HoSoSinhVien> HoSoSinhVien { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<HocPhiNganh> HocPhiNganh { get; set; }
        public virtual DbSet<KTX> KTX { get; set; }
        public virtual DbSet<MuaDongPhuc> MuaDongPhuc { get; set; }
        public virtual DbSet<NganHang> NganHang { get; set; }
        public virtual DbSet<NguoiThan> NguoiThan { get; set; }
        public virtual DbSet<SinhVien> SinhVien { get; set; }
        public virtual DbSet<ThongTinNguoiThan> ThongTinNguoiThan { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DangKyKTX>(entity =>
            {
                entity.HasKey(e => new { e.SoCCCD, e.MaPhong });

                entity.HasIndex(e => e.SoCCCD, "IX_DangKyKTX")
                    .IsUnique();

                entity.Property(e => e.SoCCCD).HasMaxLength(12);

                entity.Property(e => e.MaPhong).HasMaxLength(20);

                entity.Property(e => e.GhiChu).HasMaxLength(500);

                entity.HasOne(d => d.MaPhongNavigation)
                    .WithMany(p => p.DangKyKTX)
                    .HasForeignKey(d => d.MaPhong)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DangKyKTX_KTX");

                entity.HasOne(d => d.SoCCCDNavigation)
                    .WithOne(p => p.DangKyKTX)
                    .HasForeignKey<DangKyKTX>(d => d.SoCCCD)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DangKyKTX_SinhVien");
            });

            modelBuilder.Entity<DongPhuc>(entity =>
            {
                entity.HasKey(e => e.MaDongPhuc);

                entity.Property(e => e.MaDongPhuc).HasMaxLength(20);

                entity.Property(e => e.DonGia).HasColumnType("smallmoney");

                entity.Property(e => e.TenDongPhuc)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<HoSo>(entity =>
            {
                entity.HasKey(e => e.MaHoSo);

                entity.Property(e => e.MaHoSo).HasMaxLength(20);

                entity.Property(e => e.MoTa).HasMaxLength(200);

                entity.Property(e => e.Ten)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<HoSoSinhVien>(entity =>
            {
                entity.HasKey(e => new { e.MaHoSo, e.SoCCCD });

                entity.Property(e => e.MaHoSo).HasMaxLength(20);

                entity.Property(e => e.SoCCCD).HasMaxLength(12);

                entity.Property(e => e.DuongDan)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.HasOne(d => d.MaHoSoNavigation)
                    .WithMany(p => p.HoSoSinhVien)
                    .HasForeignKey(d => d.MaHoSo)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_HoSoSinhVien_HoSo");

                entity.HasOne(d => d.SoCCCDNavigation)
                    .WithMany(p => p.HoSoSinhVien)
                    .HasForeignKey(d => d.SoCCCD)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_HoSoSinhVien_SinhVien");
            });

            modelBuilder.Entity<HoaDon>(entity =>
            {
                entity.HasKey(e => e.MaHD);

                entity.Property(e => e.MaHD).HasMaxLength(50);

                entity.Property(e => e.MST).HasMaxLength(20);

                entity.Property(e => e.NoiDung)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.SoTien).HasColumnType("money");

                entity.Property(e => e.ThoiDiem)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<HocPhiNganh>(entity =>
            {
                entity.HasKey(e => e.MaNganh)
                    .HasName("PK_Nganh");

                entity.Property(e => e.MaNganh).HasMaxLength(20);

                entity.Property(e => e.DonGiaTC).HasColumnType("money");

                entity.Property(e => e.KinhPhiNhapHoc).HasColumnType("money");

                entity.Property(e => e.NamApDung).HasMaxLength(20);

                entity.Property(e => e.PhiBHTN).HasColumnType("money");

                entity.Property(e => e.PhiBHYT).HasColumnType("money");

                entity.Property(e => e.PhiCLC).HasColumnType("money");

                entity.Property(e => e.TenNganh)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<KTX>(entity =>
            {
                entity.HasKey(e => e.MaPhong);

                entity.Property(e => e.MaPhong).HasMaxLength(20);

                entity.Property(e => e.DonGia).HasColumnType("money");

                entity.Property(e => e.NamHoc).HasMaxLength(50);

                entity.Property(e => e.TenPhong)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<MuaDongPhuc>(entity =>
            {
                entity.HasKey(e => new { e.SoCCCD, e.MaDongPhuc })
                    .HasName("PK_MuaDongPhuc_1");

                entity.Property(e => e.SoCCCD).HasMaxLength(12);

                entity.Property(e => e.MaDongPhuc).HasMaxLength(20);

                entity.Property(e => e.KichCo)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.MaDongPhucNavigation)
                    .WithMany(p => p.MuaDongPhuc)
                    .HasForeignKey(d => d.MaDongPhuc)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_MuaDongPhuc_DongPhuc");

                entity.HasOne(d => d.SoCCCDNavigation)
                    .WithMany(p => p.MuaDongPhuc)
                    .HasForeignKey(d => d.SoCCCD)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_MuaDongPhuc_SinhVien");
            });

            modelBuilder.Entity<NganHang>(entity =>
            {
                entity.HasKey(e => e.SoCCCD)
                    .HasName("PK_GiaoVien");

                entity.Property(e => e.SoCCCD).HasMaxLength(12);

                entity.Property(e => e.DichVu)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.HoTenInTrenThe)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.NgayCap).HasColumnType("date");

                entity.Property(e => e.SDT)
                    .IsRequired()
                    .HasMaxLength(15);

                entity.HasOne(d => d.SoCCCDNavigation)
                    .WithOne(p => p.NganHang)
                    .HasForeignKey<NganHang>(d => d.SoCCCD)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_NganHang_SinhVien");
            });

            modelBuilder.Entity<NguoiThan>(entity =>
            {
                entity.HasKey(e => e.IdNguoiThan);

                entity.Property(e => e.DanToc).HasMaxLength(20);

                entity.Property(e => e.DiaChi).HasMaxLength(50);

                entity.Property(e => e.HoTen)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.NamSinh)
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.NgheNghiep).HasMaxLength(20);

                entity.Property(e => e.QuocTich).HasMaxLength(20);

                entity.Property(e => e.SDT).HasMaxLength(20);
            });

            modelBuilder.Entity<SinhVien>(entity =>
            {
                entity.HasKey(e => e.SoCCCD);

                entity.Property(e => e.SoCCCD).HasMaxLength(12);

                entity.Property(e => e.AvatarPath).HasMaxLength(200);

                entity.Property(e => e.Email).HasMaxLength(50);

                entity.Property(e => e.GioiTinh)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.HoTen)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.MaHD).HasMaxLength(50);

                entity.Property(e => e.MaNganh).HasMaxLength(20);

                entity.Property(e => e.NgaySinh).HasColumnType("date");

                entity.Property(e => e.QuocTich).HasMaxLength(20);

                entity.Property(e => e.SDT).HasMaxLength(20);

                entity.Property(e => e.TamTru).HasMaxLength(100);

                entity.Property(e => e.ThuongTru).HasMaxLength(100);

                entity.HasOne(d => d.MaHDNavigation)
                    .WithMany(p => p.SinhVien)
                    .HasForeignKey(d => d.MaHD)
                    .HasConstraintName("FK_SinhVien_HoaDon");

                entity.HasOne(d => d.MaNganhNavigation)
                    .WithMany(p => p.SinhVien)
                    .HasForeignKey(d => d.MaNganh)
                    .HasConstraintName("FK_SinhVien_Nganh");
            });

            modelBuilder.Entity<ThongTinNguoiThan>(entity =>
            {
                entity.HasKey(e => new { e.SoCCCD, e.IdNguoiThan });

                entity.Property(e => e.SoCCCD).HasMaxLength(12);

                entity.HasOne(d => d.IdNguoiThanNavigation)
                    .WithMany(p => p.ThongTinNguoiThan)
                    .HasForeignKey(d => d.IdNguoiThan)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ThongTinNguoiThan_NguoiThan");

                entity.HasOne(d => d.SoCCCDNavigation)
                    .WithMany(p => p.ThongTinNguoiThan)
                    .HasForeignKey(d => d.SoCCCD)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ThongTinNguoiThan_SinhVien");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}