// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testKetNoi.Models
{
    public partial class HoaDon
    {
        public HoaDon()
        {
            SinhVien = new HashSet<SinhVien>();
        }

        public string MaHD { get; set; }
        public decimal SoTien { get; set; }
        public string MST { get; set; }
        public string ThoiDiem { get; set; }
        public string NoiDung { get; set; }

        public virtual ICollection<SinhVien> SinhVien { get; set; }
    }
}