// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testKetNoi.Models
{
    public partial class HocPhiNganh
    {
        public HocPhiNganh()
        {
            SinhVien = new HashSet<SinhVien>();
        }

        public string MaNganh { get; set; }
        public string TenNganh { get; set; }
        public double SoTinChiHK1 { get; set; }
        public decimal DonGiaTC { get; set; }
        public decimal KinhPhiNhapHoc { get; set; }
        public decimal PhiBHYT { get; set; }
        public decimal PhiBHTN { get; set; }
        public decimal? PhiCLC { get; set; }
        public string NamApDung { get; set; }

        public virtual ICollection<SinhVien> SinhVien { get; set; }
    }
}