// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testKetNoi.Models
{
    public partial class HoSoSinhVien
    {
        public string MaHoSo { get; set; }
        public string SoCCCD { get; set; }
        public string DuongDan { get; set; }

        public virtual HoSo MaHoSoNavigation { get; set; }
        public virtual SinhVien SoCCCDNavigation { get; set; }
    }
}