// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testKetNoi.Models
{
    public partial class KTX
    {
        public KTX()
        {
            DangKyKTX = new HashSet<DangKyKTX>();
        }

        public string MaPhong { get; set; }
        public string TenPhong { get; set; }
        public string GioiTinh { get; set; }
        public short SoNguoi { get; set; }
        public decimal DonGia { get; set; }
        public string GiuongNam { get; set; }
        public string WC { get; set; }
        public string DichVuDiKem { get; set; }

        public virtual ICollection<DangKyKTX> DangKyKTX { get; set; }
    }
}