// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testKetNoi.Models
{
    public partial class MuaDongPhuc
    {
        public string SoCCCD { get; set; }
        public string MaDongPhuc { get; set; }
        public string KichCo { get; set; }
        public int SoLuong { get; set; }

        public virtual DongPhuc MaDongPhucNavigation { get; set; }
        public virtual SinhVien SoCCCDNavigation { get; set; }
    }
}