// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testKetNoi.Models
{
    public partial class NganHang
    {
        public string SoCCCD { get; set; }
        public string HoTenInTrenThe { get; set; }
        public DateTime NgayCap { get; set; }
        public string SDT { get; set; }
        public string DichVu { get; set; }

        public virtual SinhVien SoCCCDNavigation { get; set; }
    }
}