// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testKetNoi.Models
{
    public partial class NguoiThan
    {
        public NguoiThan()
        {
            ThongTinNguoiThan = new HashSet<ThongTinNguoiThan>();
        }

        public int IdNguoiThan { get; set; }
        public string HoTen { get; set; }
        public string NamSinh { get; set; }
        public string QuocTich { get; set; }
        public string DanToc { get; set; }
        public string NgheNghiep { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }

        public virtual ICollection<ThongTinNguoiThan> ThongTinNguoiThan { get; set; }
    }
}