// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testKetNoi.Models
{
    public partial class SinhVien
    {
        public SinhVien()
        {
            HoSoSinhVien = new HashSet<HoSoSinhVien>();
            MuaDongPhuc = new HashSet<MuaDongPhuc>();
            ThongTinNguoiThan = new HashSet<ThongTinNguoiThan>();
        }

        public string SoCCCD { get; set; }
        public string HoTen { get; set; }
        public string QuocTich { get; set; }
        public string GioiTinh { get; set; }
        public DateTime? NgaySinh { get; set; }
        public string ThuongTru { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string MaHD { get; set; }
        public string MaNganh { get; set; }
        public string MatKhau { get; set; }
        public string AvatarPath { get; set; }

        public virtual HoaDon MaHDNavigation { get; set; }
        public virtual HocPhiNganh MaNganhNavigation { get; set; }
        public virtual DangKyKTX DangKyKTX { get; set; }
        public virtual NganHang NganHang { get; set; }
        public virtual ICollection<HoSoSinhVien> HoSoSinhVien { get; set; }
        public virtual ICollection<MuaDongPhuc> MuaDongPhuc { get; set; }
        public virtual ICollection<ThongTinNguoiThan> ThongTinNguoiThan { get; set; }
    }
}