// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testKetNoi.Models
{
    public partial class ThongTinNguoiThan
    {
        public string SoCCCD { get; set; }
        public int IdNguoiThan { get; set; }

        public virtual NguoiThan IdNguoiThanNavigation { get; set; }
        public virtual SinhVien SoCCCDNavigation { get; set; }
    }
}